### ISSUE TITLE
feat: node selection logic for replica AzVolumeAttachment  [ETA 02/11/2022] 

### ISSUE THREAD

**Issue by sunpa93** [abhisheksinghbaghel/azuredisk-csi-driver#169]
**Is your feature request related to a problem?/Why is this needed**

Currently, the controllers rely on the total number of `AzVolumeAttachments` per node to select node to place replica `AzVolumeAttachment`.

Ideally, we should not only consider node capacity for node selection but also fault domains and availability zones.

For volumes with set node affinity, the controller should only select from the qualified nodes group and otherwise, it seems logical to keep the attachment dispersed throughout different zones to aim for a higher availability.

Explored `auto-scaler` pkg but it doesn't seem to align.

**Describe the solution you'd like in detail**

Update node-selection logic to account for the aforementioned.

**Describe alternatives you've considered**

**Additional context**

**Comment by edreed** [comment]
This was fixed by #363
