### ISSUE TITLE
bug: volume's device path cannot be found for volumes that are reported to be attached

### ISSUE THREAD

**Issue by sunpa93** [abhisheksinghbaghel/azuredisk-csi-driver#219]
**What happened**:
* Occasionally, `NodeStageVolume` repetitively fails without any recovery sequence due to `nodeserver` not being able to find the volume's device path with the given lun.
* `CloudProvisioner.PublishVolume` reports success and Azure Portal also lists the volume under given node's list of attached volumes, but volume cannot be mounted due to the abovementioned cause.
* Also, it has been observed that detaching and reattaching the volume from/to node fixes the issue.

**What you expected to happen**:
* We expect to be able to identify volume's device path if the volume is reported successfully attached to node.

**How to reproduce it**:
* Such behavior has been observed in scale tests and pod failover tests.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by edreed** [comment]
@sunpa93 Is there anything that needs to be done here since the workaround was implemented in #218?

**Comment by sunpa93** [comment]
No, I think we have done what we can on the driver side. I left the issue open so that we can track CRP issue and close upon its fix.

**Comment by edreed** [comment]
We can go ahead and close this one. The issue has been identified and we have a commitment from CRP for a fix. There's no further action we need to take here.
