### ISSUE TITLE
bug: Recovery Needed for CRIs stuck in Transient State

### ISSUE THREAD

**Issue by sunpa93** [abhisheksinghbaghel/azuredisk-csi-driver#235]
**What happened**:
CRIs sometimes get stuck in `XXXing` states (most often `Attaching` state), and until the CRI either gets updated to `XXXFailed` state or other success indicating states, there is no component within our driver that can intervene and requeue this operation. And aside from the bug we are seeing, if the controller crashes for any reason in the middle of these update operations, our CRIs will get stuck in these states and will not be able to recover.
 
On that note, our driver has a need for some kind of recovery scheme for such scenarios.

**What you expected to happen**:
To be able to control CRI transient state in an expected manner.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by edreed** [comment]
@sunpa93 This was fixed by #263, correct?

**Comment by sunpa93** [comment]
> @sunpa93 This was fixed by #263, correct?

#236 handles CRI getting stuck in transient state from non-recoverable net errors but I think we should keep this issue open to keep track of other unrecoverable errors we can encounter from cri update that can leave cri stuck in transient states (although we have not had encountered other errors that can contribute to this so far).

**Comment by edreed** [comment]
> ...keep this issue open to keep track of other unrecoverable errors we can encounter from cri update that can leave cri stuck in transient states (although we have not had encountered other errors that can contribute to this so far).

It doesn't really help to track theoretical issues with unknown root causes. Unless there is an unaddressed known condition that causes this issue, we should close it. We can always create a new one if we encounter other errors that cause this same issue.

**Comment by sunpa93** [comment]
Sounds good. Will close this issue then 👍
