### ISSUE TITLE
bug: E2E windows tests are failing due to availability zone issues

### ISSUE THREAD

**Issue by nearora-msft** [abhisheksinghbaghel/azuredisk-csi-driver#270]
**What happened**:
The windows e2e tests are failing with timeouts from this PR: https://github.com/abhisheksinghbaghel/azuredisk-csi-driver/pull/262

Link to error: https://github.com/abhisheksinghbaghel/azuredisk-csi-driver/runs/4079107647?check_suite_focus=true

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by edreed** [comment]
The pre-provisioning test are failing because the Windows cluster is now multi-zone and the disk is in a different zone than the pod:

```log
Nov  2 13:02:48.694: INFO: At 2021-11-02 12:52:38 +0000 UTC - event for azuredisk-volume-tester-vhnkm: {attachdetach-controller } FailedAttachVolume: AttachVolume.Attach failed for volume "azuredisk-896-disk.csi.azure.com-preprovsioned-pv-bdbz7" : rpc error: code = FailedPrecondition desc = attach volume "/subscriptions/***/resourceGroups/k8s-e2etest-be219890-3bcd-11ec-896f-6fabc04cfac4-rg/providers/Microsoft.Compute/disks/pre-provisioned-read-only" to instance "1199k8s00000001" failed with Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
  "error": {
    "code": "BadRequest",
    "message": "Disk /subscriptions/***/resourceGroups/k8s-e2etest-be219890-3bcd-11ec-896f-6fabc04cfac4-rg/providers/Microsoft.Compute/disks/pre-provisioned-read-only cannot be attached to the VM because it is not in zone '2'."
  }
}
Nov  2 13:02:48.694: INFO: At 2021-11-02 12:54:39 +0000 UTC - event for azuredisk-volume-tester-vhnkm: {kubelet 1199k8s00000001} FailedMount: Unable to attach or mount volumes: unmounted volumes=[test-volume-1], unattached volumes=[default-token-69bnd test-volume-1]: timed out waiting for the condition
```

The other two tests cases seem to be failing with pod scheduling failure due to node affinity; likely, the same root cause.
