### ISSUE TITLE
feat: Change storageclass name is disk2 to match other new components in the cluster

### ISSUE THREAD

**Issue by VybavaRamadoss** [abhisheksinghbaghel/azuredisk-csi-driver#304]
**What happened**:
azuredisk-premium-ssd-lrs

**What you expected to happen**:
azuredisk2-premium-ssd-lrs

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by VybavaRamadoss** [comment]
@edreed

**Comment by edreed** [comment]
@VybavaRamadoss "disk2" is only used because of SxS install. When installed to a new cluster without the V1 driver, the name will not have the "2" suffix.

**Comment by edreed** [comment]
Won't fix
