### ISSUE TITLE
bug: Replica mount should reset lost replicas once nodes are available [ETA 01/28/2022]

### ISSUE THREAD

**Issue by VybavaRamadoss** [abhisheksinghbaghel/azuredisk-csi-driver#306]
**What happened**:
3 node AKS cluster (both non-zonal and zonal). Statefulset with pvc using storageclass supporting replica mounts. replicas mounts set to 3 == the number of cluster nodes. When one node is lost or cordoned off, the number of replicas for the volume goes down to 2. When the node comes back up the number of replica attachments does not go back up to 3. 

**What you expected to happen**:
When the node comes back up the number of replica attachments goes back up to 3. 

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by VybavaRamadoss** [comment]
@edreed

**Comment by kassarl** [comment]
I'll take a look at this if no one else has picked it up yet
