### ISSUE TITLE
flake: "Should create replicas on node with matching pod node selector" test fails sometimes while updating node labels

### ISSUE THREAD

**Issue by nearora-msft** [abhisheksinghbaghel/azuredisk-csi-driver#318]
**What happened**:

**What you expected to happen**:

**How to reproduce it**:
https://github.com/abhisheksinghbaghel/azuredisk-csi-driver/runs/4286986749?check_suite_focus=true

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by edreed** [comment]
Fixed by #316
