### ISSUE TITLE
Scale test: Add cordoning to failover scale tests. Add an option to run the failover tests with maxShares > 1 disks to verify the performance gain and check the replica creation at scale.  

### ISSUE THREAD

**Issue by landreasyan** [abhisheksinghbaghel/azuredisk-csi-driver#321]
**Is your feature request related to a problem?/Why is this needed**

Currently, our scale tests implement failover by scaling down stateful sets to 0 and scaling them back up to the initial value. We need to add some logic for cordoning the nodes to insure that the pods fail over to a different node not the same one, thus imitating a more real life failover scenario. 

Additionally, the failover scale tests only run with default maxshares disk value, which will not prompt replica attachment creation. This means that we are not checking the replica attachment creation logic at scale and thus we are not verifying the performance gain for having replica attachments. 

**Describe the solution you'd like in detail**

My suggestion is to run failover tests with maxshares=2 disks. We would first cordon half of the nodes, do the initial scheduling and immediately uncordon them, hoping it won't be too late for creating replicas on the cordoned nodes. Before we scale the SS down, we need to cordon the second half of the nodes that hosts the pods. Once those nodes are cordoned, we can scale the SS back and measure the failover.

Since we are increasing the number of disk maxshares, we need to reduce the number of pods so that the cluster can still accommodate the scale test and the extra disk attachments. 

**Describe alternatives you've considered**

**Additional context**

**Comment by edreed** [comment]
Covered by #162
