### ISSUE TITLE
test: Add E2E Test to Validate Dynamic Resize [ETA 02/25/2022]

### ISSUE THREAD

**Issue by edreed** [abhisheksinghbaghel/azuredisk-csi-driver#325]
There is already an end-to-end test validating volume expansion, but it scales the StatefulSet to zero before expanding the volume. With the recently added ability to dynamically resize a disk while it is still attached to a VM, we should enhance this test to enabling testing both scenarios. The dynamic resize feature is currently in limited regions, so this test case will need to depend on being deployed to a supported region. Since the V1 driver added support for dynamic resize, the changes should be made upstream, and we'll merge with V2 afterward.

**Comment by kassarl** [comment]
Currently waiting on upstream PR to merge

**Comment by edreed** [comment]
Changes are merged upstream: kubernetes-sigs/azuredisk-csi-driver#1169

**Comment by mukhoakash** [comment]
Upstream changes are merged to mandalay
