### ISSUE TITLE
[V2] data disk count is invalid in shared disk mode [ETA 01/26/2022]

### ISSUE THREAD

**Issue by edreed** [abhisheksinghbaghel/azuredisk-csi-driver#343]
Copied from kubernetes-sigs/azuredisk-csi-driver#1097

**What happened**:
1) create a node pool with 2 nodes (DS2_v2 size), each node could attach 8 data disks at most
2) create 8 pods with one disk mount each (with `maxShares: 2`)
3) create the 9th pod with one disk mount, disk would be scheduled to one node, stuck in `ContainerCreating` state forever, and error would be like following:

```
Events:
  Type     Reason              Age               From                     Message
  ----     ------              ----              ----                     -------
  Warning  FailedScheduling    47s               default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling    47s               default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled           40s               default-scheduler        Successfully assigned default/statefulset-azuredisk-share-8 to aks-agentpool-70325192-vmss000001
  Warning  FailedAttachVolume  7s (x7 over 39s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-54c55671-22d4-4d8c-ba69-834634e65573" : rpc error: code = FailedPrecondition desc = Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: {
  "error": {
    "code": "OperationNotAllowed",
    "message": "The maximum number of data disks allowed to be attached to a VM of this size is 8.",
    "target": "dataDisks"
  }
}
```

Root cause: in shared disk mode, current maximum data disk count calculation is invalid any more, need to adjust

**What you expected to happen**:
It's ok that with with `maxShares: 2`, we could only attach 8 data disks, while the 9th pod should be in `Pending` state instead of  scheduled to one node which obviously could not attach any disk any more.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: V2
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by landreasyan** [comment]
Current handling of the case: 
Events:
  Type     Reason            Age   From                              Message
  ----     ------            ----  ----                              -------
  Warning  FailedScheduling  3m3s  csi-azuredisk-scheduler-extender  0/2 nodes are available: 2 node(s) reached the maximum number of disk attachments.
  Warning  FailedScheduling  3m1s  csi-azuredisk-scheduler-extender  0/2 nodes are available: 2 node(s) reached the maximum number of disk attachments.

![image](https://user-images.githubusercontent.com/20241928/150876555-07079446-9dd1-4516-a572-83ce98d9b4b1.png)
