### ISSUE TITLE
Scheduler Extender sometimes rejects the nodes with replicas when scheduling a pod post failover

### ISSUE THREAD

**Issue by nearora-msft** [abhisheksinghbaghel/azuredisk-csi-driver#366]
**What happened**:
Let's say a pod uses 3 volumes and the cluster nodes support maximum 4 PVs per node. When this pod is requested to be scheduled after a failover, the scheduler extender rejects the node with replicas as for this node , the number of replicas on node(3) + number of required volumes(3) is greater than the total number of pvs that can be supported by the node.

Link to code: https://github.com/abhisheksinghbaghel/azuredisk-csi-driver/blob/840111893e6efd8b0890af212e14d456d157ce01/pkg/azdiskschedulerextender/azdiskschedulerextender.go#L172

**What you expected to happen**:
Scheduler extender should prioritize there nodes instead of rejecting them.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by edreed** [comment]
@landreasyan Is there any more work here or was this fixed completely by #367?

**Comment by landreasyan** [comment]
It should be completed by #367. We can close this issue.
