### ISSUE TITLE
chore: investigate whether special support for CSI ephemeral volume or generic ephemeral volume is required

### ISSUE THREAD

**Issue by sunpa93** [abhisheksinghbaghel/azuredisk-csi-driver#383]
**What happened**:

* It needs to be further investigated whether CSI ephemeral volume or generic ephemeral volume need to inline AzVolume creation, like inline Azuredisk volumes.

**What you expected to happen**:

* If determined required, AzVolume instances need to be created for inline CSI ephemeral volume and generic ephemeral volume in Pod Controller.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nearora-msft** [comment]
1. CSI ephemeral volumes aren't supported by azure disk driver
2. For generic ephemeral volumes, create volume and controller publish volume calls are made like any other volume created using pvc, so AzVolume and AzVolumeAttachment CRIs get created as expected. There shouldn't be a need to do any special handling for this. Tested it by deploying the changes from PR: https://github.com/abhisheksinghbaghel/azuredisk-csi-driver/pull/346 and by using this example: https://github.com/abhisheksinghbaghel/azuredisk-csi-driver/blob/master/deploy/example/nginx-pod-ephemeral.yaml. The CRIs get deleted upon the deletion of pod.

**Comment by sunpa93** [comment]
Awesome. Thank you for looking into this in detail! 👍

**Comment by edreed** [comment]
Given the discussion in kubernetes-sigs/azuredisk-csi-driver#1189, I do not believe we should implement support for CSI Ephemeral Volumes in the Azure Disk CSI Driver.
