### ISSUE TITLE
Helm chart template for csi-azuredisk-controller causing empty pull policy for azuredisk-csi

### ISSUE THREAD

**Issue by sunpa93** [abhisheksinghbaghel/azuredisk-csi-driver#65]
**What happened**:

After having occasions where e2e-bootstrap was not pulling the most recent image, I noticed that the helm template for `csi-azuredisk-controller.yaml` was using `values.images.pullPolicy` instead of `values.images.azuredisk.pullPolicy`.

This was okay until `v0.5.0` because `pullPolicy` was `value`'s direct child field up until `v0.4.0` but since `v0.5.0`, `pullPolicy`s are children of individual images under `values`.

So this needs to be updated in order to avoid empty`azuredisk-csi`'s pull policy.

**What you expected to happen**:

**How to reproduce it**:

install driver via helm for `v0.5.0` and above.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by edreed** [comment]
It seems like this should affect upstream as well. We should fix it there also.

**Comment by sunpa93** [comment]
Done :)
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/861
